from .customer import CustomerViewSet
from .training_view import TrainingView
from .product_type import ProductTypeViewSet
from .computer import ComputerViewSet
from .department import DepartmentViewSet
from .employee import EmployeeViewSet
from .employee_training import EmployeeTrainingViewSet
from .payment_type import PaymentTypeViewSet
from .product import ProductViewSet
from .order import OrderViewSet
from .product_order_join import ProductOrderJoinViewSet